# coding: utf-8

"""
    currencyapi

    The currency APIs help you retrieve exchange rates and convert prices between currencies easily.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_currency_api_client
from cloudmersive_currency_api_client.api.currency_exchange_api import CurrencyExchangeApi  # noqa: E501
from cloudmersive_currency_api_client.rest import ApiException


class TestCurrencyExchangeApi(unittest.TestCase):
    """CurrencyExchangeApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_currency_api_client.api.currency_exchange_api.CurrencyExchangeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_currency_exchange_convert_currency(self):
        """Test case for currency_exchange_convert_currency

        Converts a price from the source currency into the destination currency  # noqa: E501
        """
        pass

    def test_currency_exchange_get_available_currencies(self):
        """Test case for currency_exchange_get_available_currencies

        Get a list of available currencies and corresponding countries  # noqa: E501
        """
        pass

    def test_currency_exchange_get_exchange_rate(self):
        """Test case for currency_exchange_get_exchange_rate

        Gets the exchange rate from the source currency into the destination currency  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
