# coding: utf-8

"""
    currencyapi

    The currency APIs help you retrieve exchange rates and convert prices between currencies easily.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_currency_api_client
from cloudmersive_currency_api_client.models.available_currency import AvailableCurrency  # noqa: E501
from cloudmersive_currency_api_client.rest import ApiException


class TestAvailableCurrency(unittest.TestCase):
    """AvailableCurrency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvailableCurrency(self):
        """Test AvailableCurrency"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_currency_api_client.models.available_currency.AvailableCurrency()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
