# coding: utf-8

"""
    currencyapi

    The currency APIs help you retrieve exchange rates and convert prices between currencies easily.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_currency_api_client
from cloudmersive_currency_api_client.models.available_currency_response import AvailableCurrencyResponse  # noqa: E501
from cloudmersive_currency_api_client.rest import ApiException


class TestAvailableCurrencyResponse(unittest.TestCase):
    """AvailableCurrencyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvailableCurrencyResponse(self):
        """Test AvailableCurrencyResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_currency_api_client.models.available_currency_response.AvailableCurrencyResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
