# coding: utf-8

"""
    currencyapi

    

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "cloudmersive_currency_api_client"
VERSION = "3.0.1"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools


REQUIRES = [
    "certifi>=2017.4.17",
    "python-dateutil>=2.1",
    "six>=1.10",
    "urllib3>=1.23"
]
    

setup(
    name=NAME,
    version=VERSION,
    description="currencyapi",
    author_email="",
    url="https://www.cloudmersive.com/currency-api",
    keywords=["Swagger", "currencyapi"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description=long_description,
    long_description_content_type='text/markdown'
    

)
